apiVersion: v1
kind: Service
metadata:
  name: idea
  labels:
    app: idea
spec:
  type: NodePort
  selector:
    app: idea
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080